name: Bug Report
description: Report a bug or issue with Agentary JS
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize session with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - Browser: [e.g. Chrome 120, Firefox 118]
        - agentary-js version: [e.g. 0.1.0]
        - Node.js version: [e.g. 18.17.0]
        - OS: [e.g. macOS 14.0, Windows 11]
        - WebGPU support: [Yes/No]
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code example that reproduces the issue
      render: javascript
      placeholder: |
        import { createSession } from 'agentary-js';
        // Your code here...

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Include any relevant error messages, stack traces, or console output
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, etc.)
