blank_issues_enabled: true
contact_links:
  - name: 💬 Discussion Forum
    url: https://github.com/declanhealey/agentary-js/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/declanhealey/agentary-js#readme
    about: Check the documentation for usage examples and API reference
  - name: 🚀 Examples
    url: https://github.com/declanhealey/agentary-js/tree/main/examples
    about: Browse example implementations
