import { DataType } from "@huggingface/transformers";
export type EngineKind = 'auto' | 'webgpu' | 'wasm' | 'webnn';

export interface WorkerInstance {
  worker: Worker;
  model: Model;
  initialized: boolean;
  disposed: boolean;
  inflightId: number;
}

export interface InitArgs {
  model: Model;
  engine?: EngineKind;
  hfToken?: string;
}

export interface MessageContent {
  type: 'text' | 'tool_use' | 'tool_result';
  content: string;
  toolUseId?: string; // Generated by the tool use step
}

export interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface Model {
  name: string;
  quantization: DataType;
}

export interface Tool {
  type: 'function';
  function: {
    name: string;
    description: string;
    parameters: {
      type: 'object';
      properties: Record<string, any>;
      required: string[];
    };
    implementation?: (...args: any[]) => any;
  };
}

export interface GenerateArgs {
  model?: Model;
  messages: Message[];
  max_new_tokens?: number;
  tools?: Tool[];
  stop?: string[];
  temperature?: number;
  top_p?: number;
  top_k?: number;
  repetition_penalty?: number;
  seed?: number;
  deterministic?: boolean;
}

export type InboundMessageType = 'init' | 'generate' | 'dispose';

export type InboundMessage = {
  type: InboundMessageType;
  requestId: string;
  args?: InitArgs | GenerateArgs;
}

export interface ErrorArgs {
  error: string;
}

export interface DebugArgs {
  message: string;
  data?: unknown;
}

export interface ChunkArgs {
  token: string;
  tokenId: number;
  isFirst: boolean;
  isLast: boolean;
  ttfbMs?: number;
}

export type OutboundMessageType = 'chunk' | 'ack' | 'done' | 'error' | 'debug';

export type OutboundMessage = {
  type: OutboundMessageType;
  requestId: string;
  args?: ChunkArgs | ErrorArgs | DebugArgs;
}