name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build package
        run: npm run build
        
      - name: Run tests
        run: npm test --if-present
        
      - name: Bump version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
        
      - name: Get new version
        id: version
        run: echo "new_version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            package.json
            package-lock.json
          commit-message: "chore: bump version to ${{ steps.version.outputs.new_version }}"
          title: "Release v${{ steps.version.outputs.new_version }}"
          body: |
            ## Release v${{ steps.version.outputs.new_version }}
            
            This PR bumps the version to ${{ steps.version.outputs.new_version }}.
            
            ### Changes
            - Version bump: ${{ github.event.inputs.version }}
            
            **Note:** After merging this PR, create a GitHub release with tag `v${{ steps.version.outputs.new_version }}` to trigger NPM publishing.
          branch: release/v${{ steps.version.outputs.new_version }}
          delete-branch: true
